# This file was generated by dev/generate_skeleton_def.py
#
# Next Steps:
# 1. Move this file to: src/pose_skeletons/definitions/
# 2. Edit the standard joint mapping below to map your skeleton's joints.
# 3. Register your new skeleton in src/pose_skeletons/__init__.py

from enum import IntEnum
from ..definition import SkeletonDefinition


class OptitrackJoints(IntEnum):
    Hips = 0
    Spine = 1
    Spine1 = 2
    Neck = 3
    Head = 4
    LeftShoulder = 5
    LeftArm = 6
    LeftForeArm = 7
    LeftHand = 8
    LeftHandThumb1 = 9
    LeftHandThumb2 = 10
    LeftHandThumb3 = 11
    LeftHandIndex1 = 12
    LeftHandIndex2 = 13
    LeftHandIndex3 = 14
    LeftHandMiddle1 = 15
    LeftHandMiddle2 = 16
    LeftHandMiddle3 = 17
    LeftHandRing1 = 18
    LeftHandRing2 = 19
    LeftHandRing3 = 20
    LeftHandPinky1 = 21
    LeftHandPinky2 = 22
    LeftHandPinky3 = 23
    RightShoulder = 24
    RightArm = 25
    RightForeArm = 26
    RightHand = 27
    RightHandThumb1 = 28
    RightHandThumb2 = 29
    RightHandThumb3 = 30
    RightHandIndex1 = 31
    RightHandIndex2 = 32
    RightHandIndex3 = 33
    RightHandMiddle1 = 34
    RightHandMiddle2 = 35
    RightHandMiddle3 = 36
    RightHandRing1 = 37
    RightHandRing2 = 38
    RightHandRing3 = 39
    RightHandPinky1 = 40
    RightHandPinky2 = 41
    RightHandPinky3 = 42
    LeftUpLeg = 43
    LeftLeg = 44
    LeftFoot = 45
    LeftToeBase = 46
    RightUpLeg = 47
    RightLeg = 48
    RightFoot = 49
    RightToeBase = 50


class Optitrack(SkeletonDefinition):
    def __init__(self):
        # The joint names from the BVH file.
        names = [j.name for j in OptitrackJoints]

        # The parent index for each joint. -1 for root.
        parents = [-1, 0, 1, 2, 3, 2, 5, 6, 7, 8, 9, 10, 8, 12, 13, 8, 15, 16, 8, 18, 19, 8, 21, 22, 2, 24, 25, 26, 27, 28, 29, 27, 31, 32, 27, 34, 35, 27, 37, 38, 27, 40, 41, 0, 43, 44, 45, 0, 47, 48, 49]

        super().__init__("Optitrack", names, parents)

	# --- Standard Joint Mapping ---
        # Edit these to map your skeleton's joints to the standard set.
        self.hips = OptitrackJoints.Hips
        self.spine_low = OptitrackJoints.Spine
        self.spine_mid = OptitrackJoints.Spine1
        self.spine_high = OptitrackJoints.Neck  # Often acts as spine high/neck base
        self.neck = OptitrackJoints.Neck
        self.head = OptitrackJoints.Head

        # Arm mappings: Optitrack "Shoulder" is usually Clavicle
        self.l_clavicle = OptitrackJoints.LeftShoulder
        self.l_shoulder = OptitrackJoints.LeftArm
        self.l_elbow = OptitrackJoints.LeftForeArm
        self.l_wrist = OptitrackJoints.LeftHand

        self.r_clavicle = OptitrackJoints.RightShoulder
        self.r_shoulder = OptitrackJoints.RightArm
        self.r_elbow = OptitrackJoints.RightForeArm
        self.r_wrist = OptitrackJoints.RightHand

        # Leg mappings: Optitrack "UpLeg" is Hip, "Leg" is Knee
        self.l_hip = OptitrackJoints.LeftUpLeg
        self.l_knee = OptitrackJoints.LeftLeg
        self.l_ankle = OptitrackJoints.LeftFoot
        self.l_foot = OptitrackJoints.LeftToeBase

        self.r_hip = OptitrackJoints.RightUpLeg
        self.r_knee = OptitrackJoints.RightLeg
        self.r_ankle = OptitrackJoints.RightFoot
        self.r_foot = OptitrackJoints.RightToeBase
