# This file was generated by dev/generate_skeleton_def.py
#
# Next Steps:
# 1. Move this file to: src/pose_skeletons/definitions/
# 2. Edit the standard joint mapping below to map your skeleton's joints.
# 3. Register your new skeleton in src/pose_skeletons/__init__.py

from enum import IntEnum
from ..definition import SkeletonDefinition


class XsensJoints(IntEnum):
    Hips = 0
    Chest = 1
    Chest2 = 2
    Chest3 = 3
    Chest4 = 4
    Neck = 5
    Head = 6
    RightCollar = 7
    RightShoulder = 8
    RightElbow = 9
    RightWrist = 10
    LeftCollar = 11
    LeftShoulder = 12
    LeftElbow = 13
    LeftWrist = 14
    RightHip = 15
    RightKnee = 16
    RightAnkle = 17
    RightToe = 18
    LeftHip = 19
    LeftKnee = 20
    LeftAnkle = 21
    LeftToe = 22


class Xsens(SkeletonDefinition):
    def __init__(self):
        # The joint names from the BVH file.
        names = [j.name for j in XsensJoints]

        # The parent index for each joint. -1 for root.
        parents = [-1, 0, 1, 2, 3, 4, 5, 4, 7, 8, 9, 4, 11, 12, 13, 0, 15, 16, 17, 0, 19, 20, 21]

        super().__init__("Xsens", names, parents)

        # --- Standard Joint Mapping ---
        # Edit these to map your skeleton's joints to the standard set.
        # Your joint enum is available as `XsensJoints`.
        # Example: self.hips = XsensJoints.Hips.value
# --- Standard Joint Mapping ---
        # Core
        self.hips = XsensJoints.Hips
        self.spine_low = XsensJoints.Chest      # L5/L4 region
        self.spine_mid = XsensJoints.Chest3     # T8 region
        self.spine_high = XsensJoints.Chest4    # Neck base / C7
        self.neck = XsensJoints.Neck
        self.head = XsensJoints.Head

        # Left Arm
        self.l_clavicle = XsensJoints.LeftCollar
        self.l_shoulder = XsensJoints.LeftShoulder
        self.l_elbow = XsensJoints.LeftElbow
        self.l_wrist = XsensJoints.LeftWrist

        # Right Arm
        self.r_clavicle = XsensJoints.RightCollar
        self.r_shoulder = XsensJoints.RightShoulder
        self.r_elbow = XsensJoints.RightElbow
        self.r_wrist = XsensJoints.RightWrist

        # Left Leg
        self.l_hip = XsensJoints.LeftHip
        self.l_knee = XsensJoints.LeftKnee
        self.l_ankle = XsensJoints.LeftAnkle
        self.l_foot = XsensJoints.LeftToe

        # Right Leg
        self.r_hip = XsensJoints.RightHip
        self.r_knee = XsensJoints.RightKnee
        self.r_ankle = XsensJoints.RightAnkle
        self.r_foot = XsensJoints.RightToe